from __future__ import annotations

from openscire.references.formatter.models import (
    AuthorFormat,
    CitationStyle,
    InlineFormat,
    ReferenceOrder,
    StyleConfig,
)

BUILT_IN_STYLES: dict[CitationStyle, StyleConfig] = {
    CitationStyle.APA: StyleConfig(
        name="apa",
        display_name="APA 7th Edition",
        inline_format=InlineFormat.AUTHOR_YEAR_PAREN,
        reference_order=ReferenceOrder.ALPHABETICAL,
        author_format=AuthorFormat.LAST_FIRST,
        et_al_threshold=3,
        use_ampersand=True,
        journal_italic=True,
        volume_italic=True,
        doi_links=True,
        include_issue=True,
        max_authors=20,
        reference_prefix_format="",
        format_template="{authors} ({year}). {title}. *{journal}*, *{volume}*({issue}), {pages}. https://doi.org/{doi}",
    ),
    CitationStyle.NATURE: StyleConfig(
        name="nature",
        display_name="Nature",
        inline_format=InlineFormat.NUMERIC_SUPERSCRIPT,
        reference_order=ReferenceOrder.ORDER_OF_APPEARANCE,
        author_format=AuthorFormat.FIRST_LAST,
        et_al_threshold=6,
        use_ampersand=False,
        journal_italic=False,
        volume_italic=True,
        doi_links=False,
        doi_prefix="doi:",
        include_issue=False,
        max_authors=10,
        reference_prefix_format="{number}. ",
        format_template="{authors} *{title}* *{journal}* **{volume}**, {pages} ({year}).",
    ),
    CitationStyle.SCIENCE: StyleConfig(
        name="science",
        display_name="Science",
        inline_format=InlineFormat.NUMERIC_SUPERSCRIPT,
        reference_order=ReferenceOrder.ORDER_OF_APPEARANCE,
        author_format=AuthorFormat.FIRST_LAST,
        et_al_threshold=6,
        use_ampersand=False,
        journal_italic=True,
        volume_italic=True,
        doi_links=False,
        doi_prefix="doi:",
        include_issue=False,
        max_authors=10,
        reference_prefix_format="{number}. ",
        format_template="{authors}, *{title}*, *{journal}* **{volume}**, {pages} ({year}).",
    ),
    CitationStyle.VANCOUVER: StyleConfig(
        name="vancouver",
        display_name="Vancouver",
        inline_format=InlineFormat.NUMERIC_BRACKET,
        reference_order=ReferenceOrder.ORDER_OF_APPEARANCE,
        author_format=AuthorFormat.LAST_FIRST,
        et_al_threshold=6,
        use_ampersand=False,
        journal_italic=True,
        volume_italic=False,
        doi_links=True,
        include_issue=True,
        max_authors=10,
        reference_prefix_format="{number}. ",
        format_template="{authors}. {title}. *{journal}*. {year};{volume}({issue}):{pages}.",
    ),
    CitationStyle.IEEE: StyleConfig(
        name="ieee",
        display_name="IEEE",
        inline_format=InlineFormat.NUMERIC_BRACKET,
        reference_order=ReferenceOrder.ORDER_OF_APPEARANCE,
        author_format=AuthorFormat.FIRST_LAST,
        et_al_threshold=6,
        use_ampersand=False,
        journal_italic=True,
        volume_italic=True,
        doi_links=True,
        include_issue=True,
        max_authors=10,
        reference_prefix_format="{number}. ",
        format_template='{authors}, "{title}," *{journal}*, vol. {volume}, no. {issue}, pp. {pages}, {year}.',
    ),
    CitationStyle.CHICAGO: StyleConfig(
        name="chicago",
        display_name="Chicago Manual of Style 17th",
        inline_format=InlineFormat.AUTHOR_YEAR_PAREN,
        reference_order=ReferenceOrder.ALPHABETICAL,
        author_format=AuthorFormat.LAST_FIRST,
        et_al_threshold=3,
        use_ampersand=True,
        journal_italic=True,
        volume_italic=True,
        doi_links=True,
        include_issue=True,
        max_authors=10,
        reference_prefix_format="",
        format_template='{authors}. {year}. "{title}." *{journal}* {volume}, no. {issue} ({year}): {pages}. https://doi.org/{doi}',
    ),
    CitationStyle.ACS: StyleConfig(
        name="acs",
        display_name="ACS",
        inline_format=InlineFormat.NUMERIC_SUPERSCRIPT,
        reference_order=ReferenceOrder.ORDER_OF_APPEARANCE,
        author_format=AuthorFormat.LAST_FIRST,
        et_al_threshold=10,
        use_ampersand=False,
        journal_italic=True,
        volume_italic=True,
        doi_links=False,
        doi_prefix="doi:",
        include_issue=False,
        max_authors=10,
        reference_prefix_format="{number}. ",
        format_template="{authors}. *{journal}* {year}, *{volume}*, {pages}.",
    ),
}
