# SPDX-License-Identifier: Apache-2.0

"""Bio-database bridge clients (UniProt, PDB, Entrez, AlphaFold, etc.)."""

from openscire.bridges.interpro import (
    GoTerm,
    InterProClient,
    InterProEntry,
    InterProMatch,
    InterProProteinEntry,
    InterProScanClient,
    InterProScanResult,
    LiteratureRef,
    MemberDatabaseEntry,
    SignatureDBMeta,
    SignatureDBMethod,
)
from openscire.bridges.alphafold import (
    AlphaFoldClient,
    AlphaFoldPrediction,
    DisorderReport,
    DisorderedRegion,
    DomainRegion,
    PaeMatrix,
    ResidueConfidence,
)
from openscire.bridges.entrez import (
    AssemblyRecord,
    EntrezClient,
    EntrezLink,
    EntrezLinkSet,
    EntrezSearchResult,
    EntrezSummary,
    NucleotideRecord,
    TaxonomyRecord,
)
from openscire.bridges.pdb import (
    PdbAuthor,
    PdbCitation,
    PdbClient,
    PdbCrossReference,
    PdbPolymerEntity,
    PdbQueryBuilder,
    PdbSearchResult,
    PdbStructureResult,
)
from openscire.bridges.uniprot import (
    CrossReference,
    UniProtClient,
    UniProtComment,
    UniProtFeature,
    UniProtQueryBuilder,
    UniProtResult,
    UniProtSearchResult,
)

__all__ = [
    "AlphaFoldClient",
    "AlphaFoldPrediction",
    "AssemblyRecord",
    "CrossReference",
    "GoTerm",
    "InterProClient",
    "InterProEntry",
    "InterProMatch",
    "InterProProteinEntry",
    "InterProScanClient",
    "InterProScanResult",
    "LiteratureRef",
    "MemberDatabaseEntry",
    "SignatureDBMeta",
    "SignatureDBMethod",
    "DisorderReport",
    "DisorderedRegion",
    "DomainRegion",
    "EntrezClient",
    "EntrezLink",
    "EntrezLinkSet",
    "EntrezSearchResult",
    "EntrezSummary",
    "NucleotideRecord",
    "PaeMatrix",
    "PdbAuthor",
    "PdbCitation",
    "PdbClient",
    "PdbCrossReference",
    "PdbPolymerEntity",
    "PdbQueryBuilder",
    "PdbSearchResult",
    "PdbStructureResult",
    "ResidueConfidence",
    "TaxonomyRecord",
    "UniProtClient",
    "UniProtComment",
    "UniProtFeature",
    "UniProtQueryBuilder",
    "UniProtResult",
    "UniProtSearchResult",
]
